f=open("var_ope.sh","ab")
f.write("echo \"enter var1 : \"\n")
f.write("read var1\n")
f.write("echo \"enter var2 : \"\n")
f.write("read var2\n")
f.write("((var3=var1+var2))\n")
f.write("echo \"given vars : $var1 $var2\"\n")
f.write("echo \"sum : $var3\"")
f.close()
